/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gaps.basic.Bigjack228.app;

import gaps.basic.Bigjack228.list.LinkedList;

import static gaps.basic.Bigjack228.utilities.StringUtils.join;
import static gaps.basic.Bigjack228.utilities.StringUtils.split;
import static gaps.basic.Bigjack228.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
